version: '3.9'
services:
  nodejs:
    image: node:18.16.1
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - app-network

  postgres:
    image: postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Palvin123
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:
